name: nishas_yoga
description: A Yoga Studio Management App.

publish_to: 'none'

version: 1.0.2+6

environment:
  sdk: '3.3.3'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  google_fonts: ^6.1.0
  flutter_lints: ^3.0.1
  sqflite: ^2.3.0
  path: ^1.8.3
  shared_preferences: ^2.2.2
  intl: ^0.19.0
  provider: ^6.1.1
  http: ^1.1.0
  image_picker: ^1.0.5
  country_pickers: ^2.0.0
  multiselect_formfield: ^0.1.7
  connectivity: ^3.0.6
  lottie: ^3.1.0
  timezone: ^0.9.2
  url_launcher: ^6.2.5
  contacts_service: ^0.6.3
  permission_handler: ^11.3.0
  flutter_phone_direct_caller: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/Animation.json